# Generated by Django 3.1.2 on 2020-10-28 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ytube', '0002_auto_20201028_1234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chats',
            new_name='Charts',
        ),
    ]
