# Generated by Django 3.1.2 on 2020-11-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ytube', '0003_auto_20201028_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Charts',
        ),
    ]
