# Generated by Django 3.1.2 on 2020-11-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ytube', '0005_output_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='output_sent',
            old_name='op_text',
            new_name='Op_Text',
        ),
        migrations.RenameField(
            model_name='output_sent',
            old_name='Sentiment',
            new_name='input_sentiment',
        ),
    ]
