# Generated by Django 3.1.2 on 2020-11-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytube', '0006_auto_20201108_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output_sent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
