# Generated by Django 3.1.2 on 2020-11-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ytube', '0008_auto_20201108_1956'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='output_sent',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sentiment',
            table=None,
        ),
    ]
