# Generated by Django 3.1.2 on 2020-11-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ytube', '0009_auto_20201108_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='output_sent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sentiment',
            options={},
        ),
    ]
