# Generated by Django 3.1.2 on 2020-11-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ytube', '0011_auto_20201108_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='output_sent',
            old_name='input_sentiment',
            new_name='sent_id',
        ),
    ]
