# Generated by Django 3.1.2 on 2020-11-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytube', '0012_auto_20201108_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='files',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='title',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
