# Generated by Django 3.1.2 on 2020-11-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ytube', '0013_auto_20201109_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentiment',
            name='files',
        ),
    ]
