# Generated by Django 3.1.3 on 2020-11-11 17:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ytube', '0014_remove_sentiment_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 11, 17, 13, 47, 273755, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
